## Numpy

### Key Features of NumPy
NumPy has various features that make it popular over lists.

    **N-Dimensional Arrays:** NumPy's core feature is ndarray, a N-dimensional array object that supports homogeneous data types.

    **Arrays with High Performance:** Arrays are stored in contiguous memory locations, enabling faster computations than Python lists (Please see Numpy Array vs Python List for details).

    **Broadcasting:** This allows element-wise computations between arrays of different shapes. It simplifies operations on arrays of various shapes by automatically aligning their dimensions without creating new data.

    **Vectorization:** Eliminates the need for explicit Python loops by applying operations directly on entire arrays.

    **Linear algebra:** NumPy contains routines for linear algebra operations, such as matrix multiplication, decompositions, and determinants.


### What is NumPy Used for?
With NumPy, you can perform a wide range of numerical operations, including:

Creating and manipulating arrays.
Performing element-wise and matrix operations.
Generating random numbers and statistical calculations.
Conducting linear algebra operations.
Working with Fourier transformations.
Handling missing values efficiently in datasets.

Referece:
https://www.geeksforgeeks.org/python/numpy-tutorial/

### Creating NumPy arrays 

Using ndarray : The array object is called ndarray. NumPy arrays are created using the array() function.


In [3]:
import numpy as np

# Creating Numpy arrays
# creating a 1d arrays
x = np.array([1, 2, 3])

# creating 2-d arrays 
y = np.array ([[1, 2], [3, 4]])

# creating a 3-d array 
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print (x)
print ()
print (y)
print ()
print ()
print (z)

[1 2 3]

[[1 2]
 [3 4]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Using NumPy Functions
NumPy provides convenient methods to create arrays initialized with specific values like zeros and ones:

In [7]:
a1_zeroes = np.zeros((3, 3))
print (a1_zeroes)
print()
a2_ones = np.ones((2, 3))
print (a2_ones)
print()
a3_range = np.arange(0, 10, 3)
print (a3_range)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[0 3 6 9]


In [15]:
# Numpy array indexing 

arr1d = np.array([10, 20, 30, 40, 50])

print (arr1d[0])

print (arr1d[-1])

arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

print (arr2d[0, 0])


10
50
1


In [8]:
#  Slicing in a 1-D Numpy array 
import numpy as np

ar1 = np.array([1, 2, 3,4 ,5, 6, 7, 8, 9, 0])
print (ar1)
print (type(ar1))

# print first fve elements
print (ar1[0:5])

# print in reverse order
# print (ar1[::-1])

# l1 = list(ar1[:-1])
# print (l1)
# type(l1)

print (len (ar1))
n = len(ar1)

for i in range(n):
    print (ar1[i], end='->')
print ()
print (ar1)


[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
[1 2 3 4 5]
10
1->2->3->4->5->6->7->8->9->0->
[1 2 3 4 5 6 7 8 9 0]


In [ ]:
#  Slicing in a 2-D Numpy array 

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print (f"Shape of the array: {arr.shape}")
print ()
print (f"{arr[0:2]}")
print ()
print (arr[1:4])


Shape of the array: (5, 3)

[[1 2 3]
 [4 5 6]]

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
5


In [ ]:
arr = arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
row, col = arr.shape

#  printing all the rows of the matrix is as good as printing the entire matrix
print (row, col)
for i in range(row):
    print (arr[i])


# print even rows
for i in range (row):
    if i % row == 0:
        print (arr[i])


5 3
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
[13 14 15]
[1 2 3]


In [ ]:
# How to print only the columns 
"""
1, 2, 3
4, 5, 6 
7, 8, 9

# Matrix 
a00 a01 a02
a10 a11 a12 
a20 a21 a22

# expected output 
#  printing only the columns 
[a00, a10, a20]
[a01, a11, a21]
[a02, a12, a22]

is pretty much the same as transpose of a matrix 
"""

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row, col = arr.shape
l1 = list()
res = np.empty((0, 3))
print (res)
res = np.array([]).reshape((0,col))
print (type(res))

res = arr.T
print (res)



for j in range(col):
    for i in range(row):
        # l1.append(arr[i, j])
        # print (arr[i, j])
        pass

# print (l1)

[]
<class 'numpy.ndarray'>
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [31]:
# Numpy Operations 
# Element-wise operations

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# addition 
sum = x + y 

# subtraction 
diff = x - y 

# product 
prod = x * y 

# division 
div = x / y

print (sum)
print (diff)
print (prod)
print (div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# Can you do the above with lists 
#  lists work differently 

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

s1 = a + b 
print (s1)

[1, 2, 3, 4, 5, 6, 7, 8]


In [39]:
# Numpy Binary Operations 

arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6])

sum = np.add(arr1, arr2) 
print (sum)

# sub = np.diff(arr2, arr1)

# pro = np.prod(arr2, arr1)

quo = np.divide(arr2, arr1)

print (sum)
# print (sub)
# print (pro)
print (quo)

[5 7 9]
[5 7 9]
[4.  2.5 2. ]


In [40]:
# Numpy Sorting Arrays 

dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
           
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
            
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
