## Numpy

### Key Features of NumPy
NumPy has various features that make it popular over lists.

    **N-Dimensional Arrays:** NumPy's core feature is ndarray, a N-dimensional array object that supports homogeneous data types.

    **Arrays with High Performance:** Arrays are stored in contiguous memory locations, enabling faster computations than Python lists (Please see Numpy Array vs Python List for details).

    **Broadcasting:** This allows element-wise computations between arrays of different shapes. It simplifies operations on arrays of various shapes by automatically aligning their dimensions without creating new data.

    **Vectorization:** Eliminates the need for explicit Python loops by applying operations directly on entire arrays.

    **Linear algebra:** NumPy contains routines for linear algebra operations, such as matrix multiplication, decompositions, and determinants.


### Creating NumPy arrays 

Using ndarray : The array object is called ndarray. NumPy arrays are created using the array() function.


In [3]:
import numpy as np

# Creating Numpy arrays
# creating a 1d arrays
x = np.array([1, 2, 3])

# creating 2-d arrays 
y = np.array ([[1, 2], [3, 4]])

# creating a 3-d array 
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print (x)
print ()
print (y)
print ()
print ()
print (z)

[1 2 3]

[[1 2]
 [3 4]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Using NumPy Functions
NumPy provides convenient methods to create arrays initialized with specific values like zeros and ones:

In [7]:
a1_zeroes = np.zeros((3, 3))
print (a1_zeroes)
print()
a2_ones = np.ones((2, 3))
print (a2_ones)
print()
a3_range = np.arange(0, 10, 3)
print (a3_range)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[0 3 6 9]


In [15]:
# Numpy array indexing 

arr1d = np.array([10, 20, 30, 40, 50])

print (arr1d[0])

print (arr1d[-1])

arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

print (arr2d[0, 0])


10
50
1


In [8]:
#  Slicing in a 1-D Numpy array 
import numpy as np

ar1 = np.array([1, 2, 3,4 ,5, 6, 7, 8, 9, 0])
print (ar1)
print (type(ar1))

# print first fve elements
print (ar1[0:5])

# print in reverse order
# print (ar1[::-1])

# l1 = list(ar1[:-1])
# print (l1)
# type(l1)

print (len (ar1))
n = len(ar1)

for i in range(n):
    print (ar1[i], end='->')
print ()
print (ar1)


[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
[1 2 3 4 5]
10
1->2->3->4->5->6->7->8->9->0->
[1 2 3 4 5 6 7 8 9 0]


In [ ]:
#  Slicing in a 2-D Numpy array 

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print (f"Shape of the array: {arr.shape}")
print ()
print (f"{arr[0:2]}")
print ()
print (arr[1:4])


Shape of the array: (5, 3)

[[1 2 3]
 [4 5 6]]

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
5


In [ ]:
arr = arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
row, col = arr.shape

#  printing all the rows of the matrix is as good as printing the entire matrix
print (row, col)
for i in range(row):
    print (arr[i])


# print even rows
for i in range (row):
    if i % row == 0:
        print (arr[i])


5 3
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
[13 14 15]
[1 2 3]


In [ ]:
# How to print only the columns 
"""
1, 2, 3
4, 5, 6 
7, 8, 9

# Matrix 
a00 a01 a02
a10 a11 a12 
a20 a21 a22

# expected output 
#  printing only the columns 
[a00, a10, a20]
[a01, a11, a21]
[a02, a12, a22]

is pretty much the same as transpose of a matrix 
"""

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row, col = arr.shape
l1 = list()
res = np.empty((0, 3))
print (res)
res = np.array([]).reshape((0,col))
print (type(res))



for j in range(col):
    for i in range(row):
        # l1.append(arr[i, j])
        print (arr[i, j])

# print (l1)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
4
7
2
5
8
3
6
9
