In [1]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matrix)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
matrix = []  # start with an empty list (our matrix)

for j in range(3):         # outer loop → rows
    row = []               # start a new row
    for i in range(1, 4):  # inner loop → columns
        value = i + j*3    # calculate value for this cell
        row.append(value)  # add it to the current row
    matrix.append(row)     # add the row to the matrix

print(matrix)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [2]:
mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

res = [val for row in mat for val in row]

print(res)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
# Using list comprehension

matrix = [[i+j*3 for i in range(1,4)] for j in range(3)]
print(matrix)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
# Matrix of random number
import random
matrix = [[random.randint(1, 100) for _ in range(3)] for _ in range(3)]
print(matrix)


[[73, 41, 45], [43, 82, 19], [98, 75, 98]]


In [8]:
# With Numpy
import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# Multiplication table (3×3)

matrix = []
for j in range(1, 4):        # rows
    row = []
    for i in range(1, 4):    # columns
        value = i * j        # multiplication table logic
        row.append(value)
    matrix.append(row)

print(matrix)


[[1, 2, 3], [2, 4, 6], [3, 6, 9]]


In [13]:
import random

matrix = []
for j in range(3):
    row = []
    for i in range(3):
        value = random.randint(1, 100)
        row.append(value)
    matrix.append(row)

print(matrix)


[[18, 99, 40], [95, 52, 5], [15, 27, 3]]


In [14]:
# Letters (A to I

matrix = []
ascii_A = ord('A')  # 65
for j in range(3):
    row = []
    for i in range(3):
        value = chr(ascii_A + j*3 + i)  # convert number to letter
        row.append(value)
    matrix.append(row)

print(matrix)


[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]


In [ ]:
# 3×3 matrix filled with sequential letters instead of numbers


In [15]:
# Multiplication table

matrix = [[i * j for i in range(1, 4)] for j in range(1, 4)]
print(matrix)


[[1, 2, 3], [2, 4, 6], [3, 6, 9]]


In [17]:
import random
matrix = [[random.randint(1, 100) for _ in range(3)] for _ in range(3)]
print(matrix)


[[90, 72, 81], [40, 32, 93], [86, 78, 90]]


In [18]:
# 3. Letters A–I

matrix = [[chr(ord('A') + j*3 + i) for i in range(3)] for j in range(3)]
print(matrix)


[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
