# Numpy 

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).

Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types.

The ndarray object consists of contiguous one-dimensional segment of computer memory, combined with an indexing scheme that maps each item to a location in the memory block. The memory block holds the elements in a row-major order (C style) or a column-major order (FORTRAN or MatLab style).

Reference
https://www.tutorialspoint.com/numpy/numpy_quick_guide.htm

# 

NumPy supports a much greater variety of numerical types than Python does. The following table shows different scalar data types defined in NumPy.

##Data Types & Description
bool_       Boolean (True or False) stored as a byte
int_        Default integer type (same as C long; normally either int64 or int32)
intc        Identical to C int (normally int32 or int64)
intp        Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8        Byte (-128 to 127)
int16       Integer (-32768 to 32767)
int32       Integer (-2147483648 to 2147483647)
int64       Integer (-9223372036854775808 to 9223372036854775807)
uint8       Unsigned integer (0 to 255)
uint16      Unsigned integer (0 to 65535)
uint32      Unsigned integer (0 to 4294967295)
uint64      Unsigned integer (0 to 18446744073709551615)
float_      Shorthand for float64
float16     Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32     Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64     Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_    Shorthand for complex128
complex64   Complex number, represented by two 32-bit floats (real and imaginary components)
complex128  Complex number, represented by two 64-bit floats (real and imaginary components)

NumPy numerical types are instances of dtype (data-type) objects, each having unique characteristics. The dtypes are available as np.bool_, np.float32, etc.

## Data Type Objects (dtype)

A data type object describes interpretation of fixed block of memory corresponding to an array, depending on the following aspects −

    Type of data (integer, float or Python object)

    Size of data

    Byte order (little-endian or big-endian)

    In case of structured type, the names of fields, data type of each field and part of the memory block taken by each field.

    If data type is a subarray, its shape and data type

The byte order is decided by prefixing '<' or '>' to data type. '<' means that encoding is little-endian (least significant is stored in smallest address). '>' means that encoding is big-endian (most significant byte is stored in smallest address).


A dtype object is constructed using the following syntax −
numpy.dtype(object, align, copy)

The parameters are −

    Object − To be converted to data type object

    Align − If true, adds padding to the field to make it similar to C-struct

    Copy − Makes a new copy of dtype object. If false, the result is reference to builtin data type object



In [2]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print (dt)


int32


In [5]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i8')
print (dt) 

int64


In [7]:
# using endian notation 
import numpy as np 
dt = np.dtype('>i4') 
print (dt)

>i4


The following examples show the use of structured data type. Here, the field name and the corresponding scalar data type is to be declared.

In [8]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print (dt )

[('age', 'i1')]


In [9]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a)

[(10,) (20,) (30,)]


In [10]:
# file name can be used to access content of age column 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a['age'])

[10 20 30]


The following examples define a structured data type called student with a string field 'name', an integer field 'age' and a float field 'marks'. This dtype is applied to ndarray object.

In [11]:
import numpy as np 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
print (student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [12]:

student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print (a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


Each built-in data type has a character code that uniquely identifies it.

    'b' − boolean

    'i' − (signed) integer

    'u' − unsigned integer

    'f' − floating-point

    'c' − complex-floating point

    'm' − timedelta

    'M' − datetime

    'O' − (Python) objects

    'S', 'a' − (byte-)string

    'U' − Unicode

    'V' − raw data (void)


# Numpy Array Attributes

## ndarray.shape

This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.



In [16]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a)
print (a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [15]:
#this resizes the ndarray 


a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a) 

[[1 2]
 [3 4]
 [5 6]]


In [18]:
#NumPy also provides a reshape function to resize an array.
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)
b = a.reshape(6,1) 
print (b)

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## ndarray.ndim

This array attribute returns the number of array dimensions.

In [21]:
print (b.ndim)
c = np.array([1,2,3,4,5])
c.ndim

2


1

In [23]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) 
print (a) # is a one dimensional array 

# now reshape it 
b = a.reshape(2,4,3) 
print (b )
# b is having three dimensions

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


## numpy.itemsize

This array attribute returns the length of each element of array in bytes.

In [27]:
# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


In [30]:
# dtype of array is now float32 (4 bytes) 

import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print (x.itemsize)
y = np.array(['ka','shy','ap'])
print (y.itemsize)


4
12


## numpy.flags

The ndarray object has the following attributes. Its current values are returned by this function.

Attribute & Description
C_CONTIGUOUS (C)    The data is in a single, C-style contiguous segment
F_CONTIGUOUS (F)    The data is in a single, Fortran-style contiguous segment
OWNDATA (O)         The array owns the memory it uses or borrows it from another object
WRITEABLE (W)       The data area can be written to. Setting this to False locks the data, making it read-only
ALIGNED (A)         The data and all elements are aligned appropriately for the hardware
UPDATEIFCOPY (U)    This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array

In [31]:
import numpy as np 
x = np.array([1,2,3,4,5]) 
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


## NumPy - Array Creation Routines

A new ndarray object can be constructed by any of the following array creation routines or using a low-level ndarray constructor.

numpy.empty

It creates an uninitialized array of specified shape and dtype. It uses the following constructor −

numpy.empty(shape, dtype = float, order = 'C')

The constructor takes the following parameters.

Parameter & Description
Shape   Shape of an empty array in int or tuple of int
Dtype   Desired output data type. Optional
Order   'C' for C-style row-major array, 'F' for FORTRAN style column-major array

In [34]:
import numpy as np 
xx = np.empty([3,2], dtype = int) 
print (x)

#Note − The elements in an array show random values as they are not initialized.

[[1 2]
 [3 4]
 [5 6]]


## numpy.zeros

Returns a new array of specified size, filled with zeros.

numpy.zeros(shape, dtype = float, order = 'C')

Parameter & Description
Shape   Shape of an empty array in int or sequence of int
Dtype   Desired output data type. Optional
Order   'C' for C-style row-major array, 'F' for FORTRAN style column-major array

In [37]:
import numpy as np 
x = np.zeros((5,), dtype = np.int) 
print (x)
y = np.zeros(4)
print (y)
# custom type 
import numpy as np 
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print (z)

[0 0 0 0 0]
[0. 0. 0. 0.]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## numpy.ones

Returns a new array of specified size and type, filled with ones.

numpy.ones(shape, dtype = None, order = 'C')

The constructor takes the following parameters.

Parameter & Description
Shape   Shape of an empty array in int or tuple of int
Dtype   Desired output data type. Optional
Order   'C' for C-style row-major array, 'F' for FORTRAN style column-major array


In [39]:
import numpy as np 
x = np.ones([2,2], dtype = int) 
print (x)

y = np.ones(8)
print (y)

[[1 1]
 [1 1]]
[1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# NumPy - Array From Existing Data

numpy.asarray

This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

numpy.asarray(a, dtype = None, order = None)

The constructor takes the following parameters.

a       Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists
dtype   By default, the data type of input data is applied to the resultant ndarray
order   C (row major) or F (column major). C is default

In [46]:
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
print (type(x))
a = np.asarray(x) 
print (a)
print (type(a))

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [48]:
# dtype is set 
import numpy as np 

x = [1,2,3]
print (type(x))
a = np.asarray(x, dtype = float) 
print (a)
print (type (a))

<class 'list'>
[1. 2. 3.]
<class 'numpy.ndarray'>


In [50]:
# ndarray from tuple 
import numpy as np 

x = (1,2,3) 
print (type(x))
a = np.asarray(x) 
print (a)
print (type(a))

<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>


In [52]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
print (type(x))
a = np.asarray(x) 
print (a)

<class 'list'>
[(1, 2, 3) (4, 5)]


## numpy.frombuffer

This function interprets a buffer as one-dimensional array. Any object that exposes the buffer interface is used as parameter to return an ndarray.

numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)

The constructor takes the following parameters.
Parameter & Description
buffer    Any object that exposes buffer interface
dtype     Data type of returned ndarray. Defaults to float
count     The number of items to read, default -1 means all data
offset    The starting position to read from. Default is 0


In [54]:

import numpy as np 
s = 'Hello World' 
print (s)
print (type(s))
a = np.frombuffer(s, dtype = 'S1') 
print (a)

# The above doesn't work. We're trying to convert a string (buffer) into an array. 
#A string isn't a buffer, especially not in py3, where strings are unicode.

Hello World
<class 'str'>


AttributeError: 'str' object has no attribute '__buffer__'

In [64]:
#To split string to characters 

a = np.array('hello')
print (a)
b = np.array('hello', dtype='<U5')
print (b)
c = np.array(list('hello'))
print (c)


hello
hello
['h' 'e' 'l' 'l' 'o']
b'hello'
b'hello'


In [65]:
#again this doesn't work
d = np.array(b'hello')
print (d)
e = np.array(b'hello', dtype='|S5')
print (e)
f = np.array(list(b'hello'))
print (f)

b'hello'
b'hello'
[104 101 108 108 111]


## numpy.fromiter

This function builds an ndarray object from any iterable object. A new one-dimensional array is returned by this function.

numpy.fromiter(iterable, dtype, count = -1)

Here, the constructor takes the following parameters.
Parameter & Description
iterable    Any iterable object
dtype       Data type of resultant array
count       The number of items to be read from iterator. Default is -1 which means all data to be read

The following examples show how to use the built-in range() function to return a list object. An iterator of this list is used to form an ndarray object.

In [68]:
# create list object using range function 
import numpy as np 
list = range(5) 
print (list)

range(0, 5)


In [71]:
# obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  
#print (it)

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print (x)

[0. 1. 2. 3. 4.]


In [66]:
np.fromiter('hello','S1')

array([b'h', b'e', b'l', b'l', b'o'], dtype='|S1')

In [67]:
np.fromiter('hello','U1')

array(['h', 'e', 'l', 'l', 'o'], dtype='<U1')

## NumPy - Array From Numerical Ranges

we will see how to create an array from numerical ranges.
## numpy.arange

This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −

numpy.arange(start, stop, step, dtype)

The constructor takes the following parameters.
Parameter & Description
start     The start of an interval. If omitted, defaults to 0
stop      The end of an interval (not including this number)
step      Spacing between values, default is 1
dtype     Data type of resulting ndarray. If not given, data type of input is used



In [74]:
import numpy as np 
x = np.arange(5) 
print (x)

# dtype set 
y = np.arange(5, dtype = float)
print (y)

z = np.arange(10,20,2) 
print (z)


[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[10 12 14 16 18]


## numpy.linspace

This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

numpy.linspace(start, stop, num, endpoint, retstep, dtype)

The constructor takes the following parameters.
Parameter & Description
start     The starting value of the sequence
stop      The end value of the sequence, included in the sequence if endpoint set to true
num       The number of evenly spaced samples to be generated. Default is 50
endpoint  True by default, hence the stop value is included in the sequence. If false, it is not included
retstep   If true, returns samples and step between the consecutive numbers
dtype     Data type of output ndarray


In [78]:
x = np.linspace(10,20,5) 
print (x)

# endpoint set to false 
y = np.linspace(10,20, 5, endpoint = False) 
print (y)

# find retstep value
z = np.linspace(1,2,5, retstep = True) 
print (z)

[10.  12.5 15.  17.5 20. ]
[10. 12. 14. 16. 18.]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


## numpy.logspace

This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

numpy.logspace(start, stop, num, endpoint, base, dtype)

Following parameters determine the output of logspace function.
Parameter & Description
start     The starting point of the sequence is basestart
stop      The final value of sequence is basestop
num       The number of values between the range. Default is 50
endpoint  If true, stop is the last value in the range
base      Base of log space, default is 10
dtype     Data type of output array. If not given, it depends upon other input arguments

So, What is a logscale ?


The following examples will help you understand the logspace function.

In [79]:
import numpy as np 
# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) 
print (a)

b = np.logspace(1,10,num = 10, base = 2) 
print (b)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


## NumPy - Indexing & Slicing

Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects.

As mentioned earlier, items in ndarray object follows zero-based index. Three types of indexing methods are available − field access, basic slicing and advanced indexing.

Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [81]:
a = np.arange(10) 
s = slice(2,7,2) 

print (a[s])

'''
In the above example, an ndarray object is prepared by arange() function. Then a slice object is defined with start, stop, 
and step values 2, 7, and 2 respectively. 
When this slice object is passed to the ndarray, a part of it starting with index 2 up to 7 with a step of 2 is sliced.

The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the 
ndarray object.
'''

[2 4 6]


In [82]:
#giving slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object.
a = np.arange(10) 
print (a)
b = a[2:7:2] 
print (b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [86]:
# slice single item 
a = np.arange(10) 
b = a[5] 
print (b)
c= a[5:]
print (c)
d = a[4:9]
print (d)

5
[5 6 7 8 9]
[4 5 6 7 8]


In [89]:
#appliying the same to multi-dimesional arrays

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)

# slice items starting from index
print ('Now we will slice the array from the index a[1:]' )
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [90]:
#Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. 
#If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.

# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:' )
print (a )
print ('\n'  )

# this returns array of items in the second column 
print ('The items in the second column are:'  )
print (a[...,1] )
print ('\n'  )

# Now we will slice all items from the second row 
print ('The items in the second row are:' )
print (a[1,...] )
print ('\n'  )

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:' )
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
